qkd_device:
  host: localhost
  port: 6000
  role: receiver
qkdm:
  id: qkdm2
  ip: 127.0.0.1
  key_size: 128
  max_key_count: 20
  dest_ID: qkdm1
  dest_IP: 127.0.0.1
  dest_port: 5000
  init: true
  port: 5001
  protocol: fake
mongo_db:
  auth_src: admin
  db: qkdm1
  host: localhost
  password: rootpwd
  port: 27017
  user: rootuser
vault:
  host: localhost
  port: 8200
  secret_engine: qkdm1
  token: s.smxNXOLalSXWBWZ0gIcQrIbg