mongo_db:
  auth_src: admin
  db: qkdm1
  host: localhost
  password: 91bd5a35f67a48bcb264c4049b960781
  port: 27017
  user: qkdm1
qkd_device:
  host: localhost
  port: 6000
  role: sender
qkdm:
  ID: qkdm1
  IP: 127.0.0.1
  KEY_SIZE: 128
  MAX_KEY_COUNT: 20
  dest_ID: qkdm2
  dest_IP: 127.0.0.1
  dest_port: 5001
  init: true
  port: 5000
  protocol: fake
vault:
  host: localhost
  port: 8200
  secret_engine: qkdm1
  token: s.sYPZJFqxAnAP68fSaiESC2Ec
