qkdm:
  QKDM_ID: qkdm1
  MAX_KEY_COUNT: 100
  KEY_SIZE: 256
  protocol: fake 
  destination_QKS: qks2 
  destination_QKDM: qkdm2
  init: false 

mongo_db:
  host: 
  port: 
  user: 
  password: 
  auth_src : 
  db_name : 

vault: 
  host : 
  port : 
  token : 
