mongo_db:
  auth_src: admin
  db: qkdm1
  host: localhost
  password: a140ea40a9474cf38c24532a259b4d75
  port: 27017
  user: qkdm1
qkd_device:
  host: localhost
  port: 6000
  role: sender
qkdm:
  dest_ID: qkdm2
  dest_IP: 127.0.0.1
  dest_port: 5001
  id: qkdm1
  init: false
  ip: 127.0.0.1
  key_size: 128
  max_key_count: 20
  port: 5000
  protocol: fake
qks:
  dest_id: qks2
  src_id: qks1
  src_ip: 127.0.0.1
  src_port: 4000
vault:
  host: localhost
  port: 8200
  secret_engine: qkdm1
  token: s.fCWVP4sOMD4DckTTndtGRPzS
