qkd_device:
  host: 172.18.0.101
  port: 6000
  role: receiver
qkdm:
  id: qkdm2a
  ip: 172.18.0.102
  key_size: 128
  max_key_count: 20
  dest_ID: qkdm1
  dest_IP: 172.18.0.101
  dest_port: 5000
  init: false
  port: 5000
  protocol: fake
