qkd_device:
  host: 172.18.0.100
  port: 6000
  role: receiver
qkdm:
  id: qkdm3
  ip: 172.18.0.103
  key_size: 128
  max_key_count: 20
  dest_ID: qkdm2b
  dest_IP: 172.18.0.100
  dest_port: 5000
  init: false
  port: 5000
  protocol: fake
