qkd_device:
  host: 172.18.0.102
  port: 6000
  role: sender
qkdm:
  dest_ID: qkdm2a
  dest_IP: 172.18.0.102
  dest_port: 5000
  id: qkdm1
  init: false
  ip: 172.18.0.101
  key_size: 128
  max_key_count: 100
  port: 5000
  protocol: fake
keycloak: 
  realm: qks
  address: 172.18.0.40
  port : 8080
  client_id: qks
  client_secret : 1b64ec08-e59f-43be-b10b-e4810de5191a
  username : qkdm1
  password : password
  


